const things_to_do =  [
        "Laugh hystarically for no reason at all",
        "Jump on your bed!",
        "Draw",
        "Dance to music that is epically epic",
        "Teenager Post.",
        "Text/Call your parents and tell them you are up in your room.",
        "Text/Call your best friend and tell them you are up in your room.",
        "Scream out of your window then quickly close the window and hide somewhere.",
        "Play an instrument that you may have VERY LOUDLY!",
        "Cover your floor with clothing!",
        "Sing. Doesn't matter if you can or can not sing. Just sing your little heart out. Loudly.",
        "Watch avengers end game!",
        "Talk to a pillow.",
        "Start a one person riot",
        "Rearrange things.",
        "Create something from random objects around your room.",
        "Throw something out of your window. Then laugh hystarically to someone outside.",
        "Try to find money under your bed, in your closet/dresser. If you do, yell hallelujah!",
        "Just jam out to a song in your head.",
        "Pretend you are on a lake. The floor is your river, the bed is your boat, and a hanger you can find with a belt on it is your fishing hook. Room fishing!",
        "Find Narnia. Again.",
        "Hide under your bed for 15 minutes. Then come out acting like a grizzly bear.",
        "Invite friends over, and make them come in through the window!",
        "Call everyone/thing around you chica",
        "Watch birds fly in the sky and mimic them.",
        "Text random friends, I hid the body...",
        "Sleep",
        "Surf the tv channels!"
    ]

export default things_to_do;